# Generated by Django 3.2.2 on 2021-10-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
