# Generated by Django 3.2.2 on 2021-10-10 17:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211010_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
