# Generated by Django 3.2.2 on 2021-10-13 13:23

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
