# Generated by Django 3.2.2 on 2021-10-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211013_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='images',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='hi.png', upload_to='uploads/'),
        ),
    ]
